# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails_admin_import}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steph Skardal"]
  s.date = %q{2012-01-27}
  s.email = %q{steph@endpoint.com}
  s.extra_rdoc_files = []
  s.files = [
    "app/controllers/rails_admin_import/base_controller.rb",
    "app/views/rails_admin/main/import.html.erb",
    "config/locales/rails_admin_import.en.yml",
    "config/routes.rb",
    "lib/engine.rb",
    "lib/rails_admin_import/import.rb",
    "lib/rails_admin_import.rb",
    "Rakefile",
    "README.md",
    "VERSION"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Description of your gem}
  s.test_files = []

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

