source 'https://rubygems.org'

gem 'rails', '~> 5.1'

group :active_record do
  case ENV['CI_DB_ADAPTER']
  when 'mysql2'
    gem 'mysql2', '~> 0.4.4'
  when 'postgresql'
    gem 'pg', '>= 0.14'
  else
    gem 'sqlite3', '~> 1.3.13'
  end
end

group :mongoid do
  gem 'mongoid', '~> 6.0'
end

gem 'rails_admin', '~> 2.0'
gem 'rails_admin_import', path: '../../'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3'

gem 'pry-byebug'
