source 'https://rubygems.org'

gem 'rails', '~> 4.0'

group :active_record do
  case ENV['CI_DB_ADAPTER']
  when 'mysql2'
    gem 'mysql2', '~> 0.3.14'
  when 'postgresql'
    gem 'pg', '>= 0.14'
  else
    gem 'sqlite3', '>= 1.3'
  end
end

group :mongoid do
  gem 'mongoid', '~> 4.0'
end

gem 'rails_admin', '~> 0.6'
gem 'rails_admin_import', path: '../../'

gem 'sass-rails', '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3'

gem 'pry'
gem 'pry-byebug'
